### ISSUE TITLE
Advertisement & general Money-Makings

### ISSUE THREAD

**Issue by SchwarzSkills** [Gronkdalonka/SportDuell#8]
Another option would be to implement advertisement, either as a popup-window or in some extra section on the bottom of the page or something.

Pretty straight forward that.

Also we could look for sponsors, that have something to do with sports. Options would be to name specific workouts after them, or to hold some tournaments with their name branded as the title. They could also offer some prices to the winner(s) of those tournaments.

Another thing that could be making some money for us, would be to establish a "Pro-League" (working title) every month / fourth of a year / half a year, where you have to pay to enter and can win a prize for being 1st / 2nd / 3rd, maybe sponsored by companies as well.

**Comment by SvenjaJunge** [comment]
Nice idea.

**Comment by Gronkdalonka** [comment]
i will close this as i think we don't need this anymore
